name: JUnit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 16 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Adoptium JDK
          java-version: '21'  # Change based on your project

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Run JUnit Tests with Maven
        run: mvn test

      - name: Upload Test Results (JUnit Reports)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: target/surefire-reports/